function initData(imageName) {
    var s = 0;
    if (imageName == "veryhuo.com_pkp_102.jpg"||imageName == "veryhuo.com_pkp_111.jpg"||imageName == "veryhuo.com_pkp_125.jpg"||imageName == "veryhuo.com_pkp_140.jpg"||imageName == "veryhuo.com_pkp_154.jpg"||imageName == "veryhuo.com_pkp_163.jpg"||imageName == "veryhuo.com_pkp_177.jpg"||imageName == "veryhuo.com_pkp_192.jpg"||imageName == "veryhuo.com_pkp_206.jpg"||imageName == "veryhuo.com_pkp_21.jpg"||imageName == "veryhuo.com_pkp_215.jpg"||imageName == "veryhuo.com_pkp_229.jpg"||imageName == "veryhuo.com_pkp_244.jpg"||imageName == "veryhuo.com_pkp_258.jpg"||imageName == "veryhuo.com_pkp_267.jpg"||imageName == "veryhuo.com_pkp_281.jpg"||imageName == "veryhuo.com_pkp_296.jpg"||imageName == "veryhuo.com_pkp_310.jpg"||imageName == "veryhuo.com_pkp_319.jpg"||imageName == "veryhuo.com_pkp_333.jpg"||imageName == "veryhuo.com_pkp_348.jpg"||imageName == "veryhuo.com_pkp_36.jpg"||imageName == "veryhuo.com_pkp_362.jpg"||imageName == "veryhuo.com_pkp_371.jpg"||imageName == "veryhuo.com_pkp_385.jpg"||imageName == "veryhuo.com_pkp_400.jpg"||imageName == "veryhuo.com_pkp_414.jpg"||imageName == "veryhuo.com_pkp_50.jpg"||imageName == "veryhuo.com_pkp_59.jpg"||imageName == "veryhuo.com_pkp_7.jpg"||imageName == "veryhuo.com_pkp_73.jpg"||imageName == "veryhuo.com_pkp_88.jpg") {
        s = 1;
    }  else if (imageName == "veryhuo.com_pkp_103.jpg"||imageName == "veryhuo.com_pkp_112.jpg"||imageName == "veryhuo.com_pkp_126.jpg"||imageName == "veryhuo.com_pkp_141.jpg"||imageName == "veryhuo.com_pkp_155.jpg"||imageName == "veryhuo.com_pkp_164.jpg"||imageName == "veryhuo.com_pkp_178.jpg"||imageName == "veryhuo.com_pkp_193.jpg"||imageName == "veryhuo.com_pkp_207.jpg"||imageName == "veryhuo.com_pkp_216.jpg"||imageName == "veryhuo.com_pkp_22.jpg"||imageName == "veryhuo.com_pkp_230.jpg"||imageName == "veryhuo.com_pkp_245.jpg"||imageName == "veryhuo.com_pkp_259.jpg"||imageName == "veryhuo.com_pkp_268.jpg"||imageName == "veryhuo.com_pkp_282.jpg"||imageName == "veryhuo.com_pkp_297.jpg"||imageName == "veryhuo.com_pkp_311.jpg"||imageName == "veryhuo.com_pkp_320.jpg"||imageName == "veryhuo.com_pkp_334.jpg"||imageName == "veryhuo.com_pkp_349.jpg"||imageName == "veryhuo.com_pkp_363.jpg"||imageName == "veryhuo.com_pkp_37.jpg"||imageName == "veryhuo.com_pkp_372.jpg"||imageName == "veryhuo.com_pkp_386.jpg"||imageName == "veryhuo.com_pkp_401.jpg"||imageName == "veryhuo.com_pkp_415.jpg"||imageName == "veryhuo.com_pkp_51.jpg"||imageName == "veryhuo.com_pkp_60.jpg"||imageName == "veryhuo.com_pkp_74.jpg"||imageName == "veryhuo.com_pkp_8.jpg"||imageName == "veryhuo.com_pkp_89.jpg") {
        s = 2;
    } else if (imageName == "veryhuo.com_pkp_113.jpg"||imageName == "veryhuo.com_pkp_127.jpg"||imageName == "veryhuo.com_pkp_128.jpg"||imageName == "veryhuo.com_pkp_142.jpg"||imageName == "veryhuo.com_pkp_165.jpg"||imageName == "veryhuo.com_pkp_179.jpg"||imageName == "veryhuo.com_pkp_180.jpg"||imageName == "veryhuo.com_pkp_194.jpg"||imageName == "veryhuo.com_pkp_217.jpg"||imageName == "veryhuo.com_pkp_23.jpg"||imageName == "veryhuo.com_pkp_231.jpg"||imageName == "veryhuo.com_pkp_232.jpg"||imageName == "veryhuo.com_pkp_24.jpg"||imageName == "veryhuo.com_pkp_246.jpg"||imageName == "veryhuo.com_pkp_269.jpg"||imageName == "veryhuo.com_pkp_283.jpg"||imageName == "veryhuo.com_pkp_284.jpg"||imageName == "veryhuo.com_pkp_298.jpg"||imageName == "veryhuo.com_pkp_321.jpg"||imageName == "veryhuo.com_pkp_335.jpg"||imageName == "veryhuo.com_pkp_336.jpg"||imageName == "veryhuo.com_pkp_350.jpg"||imageName == "veryhuo.com_pkp_373.jpg"||imageName == "veryhuo.com_pkp_38.jpg"||imageName == "veryhuo.com_pkp_387.jpg"||imageName == "veryhuo.com_pkp_388.jpg"||imageName == "veryhuo.com_pkp_402.jpg"||imageName == "veryhuo.com_pkp_61.jpg"||imageName == "veryhuo.com_pkp_75.jpg"||imageName == "veryhuo.com_pkp_76.jpg"||imageName == "veryhuo.com_pkp_9.jpg"||imageName == "veryhuo.com_pkp_90.jpg") {
        s = 3;
    } else if (imageName == "veryhuo.com_pkp_10.jpg"||imageName == "veryhuo.com_pkp_114.jpg"||imageName == "veryhuo.com_pkp_129.jpg"||imageName == "veryhuo.com_pkp_139.jpg"||imageName == "veryhuo.com_pkp_143.jpg"||imageName == "veryhuo.com_pkp_166.jpg"||imageName == "veryhuo.com_pkp_181.jpg"||imageName == "veryhuo.com_pkp_191.jpg"||imageName == "veryhuo.com_pkp_195.jpg"||imageName == "veryhuo.com_pkp_218.jpg"||imageName == "veryhuo.com_pkp_233.jpg"||imageName == "veryhuo.com_pkp_243.jpg"||imageName == "veryhuo.com_pkp_247.jpg"||imageName == "veryhuo.com_pkp_25.jpg"||imageName == "veryhuo.com_pkp_270.jpg"||imageName == "veryhuo.com_pkp_285.jpg"||imageName == "veryhuo.com_pkp_295.jpg"||imageName == "veryhuo.com_pkp_299.jpg"||imageName == "veryhuo.com_pkp_322.jpg"||imageName == "veryhuo.com_pkp_337.jpg"||imageName == "veryhuo.com_pkp_347.jpg"||imageName == "veryhuo.com_pkp_35.jpg"||imageName == "veryhuo.com_pkp_351.jpg"||imageName == "veryhuo.com_pkp_374.jpg"||imageName == "veryhuo.com_pkp_389.jpg"||imageName == "veryhuo.com_pkp_39.jpg"||imageName == "veryhuo.com_pkp_399.jpg"||imageName == "veryhuo.com_pkp_403.jpg"||imageName == "veryhuo.com_pkp_62.jpg"||imageName == "veryhuo.com_pkp_77.jpg"||imageName == "veryhuo.com_pkp_87.jpg"||imageName == "veryhuo.com_pkp_91.jpg") {
        s = 4;
    } else if (imageName == "veryhuo.com_pkp_11.jpg"||imageName == "veryhuo.com_pkp_115.jpg"||imageName == "veryhuo.com_pkp_130.jpg"||imageName == "veryhuo.com_pkp_144.jpg"||imageName == "veryhuo.com_pkp_150.jpg"||imageName == "veryhuo.com_pkp_167.jpg"||imageName == "veryhuo.com_pkp_182.jpg"||imageName == "veryhuo.com_pkp_196.jpg"||imageName == "veryhuo.com_pkp_202.jpg"||imageName == "veryhuo.com_pkp_219.jpg"||imageName == "veryhuo.com_pkp_234.jpg"||imageName == "veryhuo.com_pkp_248.jpg"||imageName == "veryhuo.com_pkp_254.jpg"||imageName == "veryhuo.com_pkp_26.jpg"||imageName == "veryhuo.com_pkp_271.jpg"||imageName == "veryhuo.com_pkp_286.jpg"||imageName == "veryhuo.com_pkp_300.jpg"||imageName == "veryhuo.com_pkp_306.jpg"||imageName == "veryhuo.com_pkp_323.jpg"||imageName == "veryhuo.com_pkp_338.jpg"||imageName == "veryhuo.com_pkp_352.jpg"||imageName == "veryhuo.com_pkp_358.jpg"||imageName == "veryhuo.com_pkp_375.jpg"||imageName == "veryhuo.com_pkp_390.jpg"||imageName == "veryhuo.com_pkp_40.jpg"||imageName == "veryhuo.com_pkp_404.jpg"||imageName == "veryhuo.com_pkp_410.jpg"||imageName == "veryhuo.com_pkp_46.jpg"||imageName == "veryhuo.com_pkp_63.jpg"||imageName == "veryhuo.com_pkp_78.jpg"||imageName == "veryhuo.com_pkp_92.jpg"||imageName == "veryhuo.com_pkp_98.jpg") {
        s = 5;
    } else if (imageName == "veryhuo.com_pkp_104.jpg"||imageName == "veryhuo.com_pkp_116.jpg"||imageName == "veryhuo.com_pkp_12.jpg"||imageName == "veryhuo.com_pkp_131.jpg"||imageName == "veryhuo.com_pkp_145.jpg"||imageName == "veryhuo.com_pkp_156.jpg"||imageName == "veryhuo.com_pkp_168.jpg"||imageName == "veryhuo.com_pkp_183.jpg"||imageName == "veryhuo.com_pkp_197.jpg"||imageName == "veryhuo.com_pkp_208.jpg"||imageName == "veryhuo.com_pkp_220.jpg"||imageName == "veryhuo.com_pkp_235.jpg"||imageName == "veryhuo.com_pkp_249.jpg"||imageName == "veryhuo.com_pkp_260.jpg"||imageName == "veryhuo.com_pkp_27.jpg"||imageName == "veryhuo.com_pkp_272.jpg"||imageName == "veryhuo.com_pkp_287.jpg"||imageName == "veryhuo.com_pkp_301.jpg"||imageName == "veryhuo.com_pkp_312.jpg"||imageName == "veryhuo.com_pkp_324.jpg"||imageName == "veryhuo.com_pkp_339.jpg"||imageName == "veryhuo.com_pkp_353.jpg"||imageName == "veryhuo.com_pkp_364.jpg"||imageName == "veryhuo.com_pkp_376.jpg"||imageName == "veryhuo.com_pkp_391.jpg"||imageName == "veryhuo.com_pkp_405.jpg"||imageName == "veryhuo.com_pkp_41.jpg"||imageName == "veryhuo.com_pkp_416.jpg"||imageName == "veryhuo.com_pkp_52.jpg"||imageName == "veryhuo.com_pkp_64.jpg"||imageName == "veryhuo.com_pkp_79.jpg"||imageName == "veryhuo.com_pkp_93.jpg") {
        s = 6;
    } else if (imageName == "veryhuo.com_pkp_106.jpg"||imageName == "veryhuo.com_pkp_118.jpg"||imageName == "veryhuo.com_pkp_132.jpg"||imageName == "veryhuo.com_pkp_14.jpg"||imageName == "veryhuo.com_pkp_146.jpg"||imageName == "veryhuo.com_pkp_158.jpg"||imageName == "veryhuo.com_pkp_170.jpg"||imageName == "veryhuo.com_pkp_184.jpg"||imageName == "veryhuo.com_pkp_198.jpg"||imageName == "veryhuo.com_pkp_2.jpg"||imageName == "veryhuo.com_pkp_210.jpg"||imageName == "veryhuo.com_pkp_222.jpg"||imageName == "veryhuo.com_pkp_236.jpg"||imageName == "veryhuo.com_pkp_250.jpg"||imageName == "veryhuo.com_pkp_262.jpg"||imageName == "veryhuo.com_pkp_274.jpg"||imageName == "veryhuo.com_pkp_28.jpg"||imageName == "veryhuo.com_pkp_288.jpg"||imageName == "veryhuo.com_pkp_302.jpg"||imageName == "veryhuo.com_pkp_314.jpg"||imageName == "veryhuo.com_pkp_326.jpg"||imageName == "veryhuo.com_pkp_340.jpg"||imageName == "veryhuo.com_pkp_354.jpg"||imageName == "veryhuo.com_pkp_366.jpg"||imageName == "veryhuo.com_pkp_378.jpg"||imageName == "veryhuo.com_pkp_392.jpg"||imageName == "veryhuo.com_pkp_406.jpg"||imageName == "veryhuo.com_pkp_42.jpg"||imageName == "veryhuo.com_pkp_54.jpg"||imageName == "veryhuo.com_pkp_66.jpg"||imageName == "veryhuo.com_pkp_80.jpg"||imageName == "veryhuo.com_pkp_94.jpg") {
        s = 7;
    } else if (imageName == "veryhuo.com_pkp_117.jpg"||imageName == "veryhuo.com_pkp_119.jpg"||imageName == "veryhuo.com_pkp_13.jpg"||imageName == "veryhuo.com_pkp_133.jpg"||imageName == "veryhuo.com_pkp_147.jpg"||imageName == "veryhuo.com_pkp_15.jpg"||imageName == "veryhuo.com_pkp_169.jpg"||imageName == "veryhuo.com_pkp_171.jpg"||imageName == "veryhuo.com_pkp_185.jpg"||imageName == "veryhuo.com_pkp_199.jpg"||imageName == "veryhuo.com_pkp_221.jpg"||imageName == "veryhuo.com_pkp_223.jpg"||imageName == "veryhuo.com_pkp_237.jpg"||imageName == "veryhuo.com_pkp_251.jpg"||imageName == "veryhuo.com_pkp_273.jpg"||imageName == "veryhuo.com_pkp_275.jpg"||imageName == "veryhuo.com_pkp_289.jpg"||imageName == "veryhuo.com_pkp_29.jpg"||imageName == "veryhuo.com_pkp_303.jpg"||imageName == "veryhuo.com_pkp_325.jpg"||imageName == "veryhuo.com_pkp_327.jpg"||imageName == "veryhuo.com_pkp_341.jpg"||imageName == "veryhuo.com_pkp_355.jpg"||imageName == "veryhuo.com_pkp_377.jpg"||imageName == "veryhuo.com_pkp_379.jpg"||imageName == "veryhuo.com_pkp_393.jpg"||imageName == "veryhuo.com_pkp_407.jpg"||imageName == "veryhuo.com_pkp_43.jpg"||imageName == "veryhuo.com_pkp_65.jpg"||imageName == "veryhuo.com_pkp_67.jpg"||imageName == "veryhuo.com_pkp_81.jpg"||imageName == "veryhuo.com_pkp_95.jpg") {
        s = 8;
    } else if (imageName == "veryhuo.com_pkp_1.jpg"||imageName == "veryhuo.com_pkp_105.jpg"||imageName == "veryhuo.com_pkp_120.jpg"||imageName == "veryhuo.com_pkp_134.jpg"||imageName == "veryhuo.com_pkp_148.jpg"||imageName == "veryhuo.com_pkp_157.jpg"||imageName == "veryhuo.com_pkp_16.jpg"||imageName == "veryhuo.com_pkp_172.jpg"||imageName == "veryhuo.com_pkp_186.jpg"||imageName == "veryhuo.com_pkp_200.jpg"||imageName == "veryhuo.com_pkp_209.jpg"||imageName == "veryhuo.com_pkp_224.jpg"||imageName == "veryhuo.com_pkp_238.jpg"||imageName == "veryhuo.com_pkp_252.jpg"||imageName == "veryhuo.com_pkp_261.jpg"||imageName == "veryhuo.com_pkp_276.jpg"||imageName == "veryhuo.com_pkp_290.jpg"||imageName == "veryhuo.com_pkp_30.jpg"||imageName == "veryhuo.com_pkp_304.jpg"||imageName == "veryhuo.com_pkp_313.jpg"||imageName == "veryhuo.com_pkp_328.jpg"||imageName == "veryhuo.com_pkp_342.jpg"||imageName == "veryhuo.com_pkp_356.jpg"||imageName == "veryhuo.com_pkp_365.jpg"||imageName == "veryhuo.com_pkp_380.jpg"||imageName == "veryhuo.com_pkp_394.jpg"||imageName == "veryhuo.com_pkp_408.jpg"||imageName == "veryhuo.com_pkp_44.jpg"||imageName == "veryhuo.com_pkp_53.jpg"||imageName == "veryhuo.com_pkp_68.jpg"||imageName == "veryhuo.com_pkp_82.jpg"||imageName == "veryhuo.com_pkp_96.jpg") {
        s = 9;
    } else {
        s = 0;
    }
    return s;
}