function initData(imageName) {
    var s = 0;
    if (imageName == "veryhuo.com_pkp_102.jpg" || imageName == "veryhuo.com_pkp_111.jpg" || imageName == "veryhuo.com_pkp_125.jpg" || imageName == "veryhuo.com_pkp_140.jpg" || imageName == "veryhuo.com_pkp_154.jpg" || imageName == "veryhuo.com_pkp_163.jpg" || imageName == "veryhuo.com_pkp_177.jpg" || imageName == "veryhuo.com_pkp_192.jpg" || imageName == "veryhuo.com_pkp_206.jpg" || imageName == "veryhuo.com_pkp_21.jpg" || imageName == "veryhuo.com_pkp_215.jpg" || imageName == "veryhuo.com_pkp_229.jpg" || imageName == "veryhuo.com_pkp_244.jpg" || imageName == "veryhuo.com_pkp_258.jpg" || imageName == "veryhuo.com_pkp_267.jpg" || imageName == "veryhuo.com_pkp_281.jpg" || imageName == "veryhuo.com_pkp_296.jpg" || imageName == "veryhuo.com_pkp_310.jpg" || imageName == "veryhuo.com_pkp_319.jpg" || imageName == "veryhuo.com_pkp_333.jpg" || imageName == "veryhuo.com_pkp_348.jpg" || imageName == "veryhuo.com_pkp_36.jpg" || imageName == "veryhuo.com_pkp_362.jpg" || imageName == "veryhuo.com_pkp_371.jpg" || imageName == "veryhuo.com_pkp_385.jpg" || imageName == "veryhuo.com_pkp_400.jpg" || imageName == "veryhuo.com_pkp_414.jpg" || imageName == "veryhuo.com_pkp_50.jpg" || imageName == "veryhuo.com_pkp_59.jpg" || imageName == "veryhuo.com_pkp_7.jpg" || imageName == "veryhuo.com_pkp_73.jpg" || imageName == "veryhuo.com_pkp_88.jpg") {
        s = 1;
    } else if (imageName == "veryhuo.com_pkp_103.jpg" || imageName == "veryhuo.com_pkp_112.jpg" || imageName == "veryhuo.com_pkp_126.jpg" || imageName == "veryhuo.com_pkp_141.jpg" || imageName == "veryhuo.com_pkp_155.jpg" || imageName == "veryhuo.com_pkp_164.jpg" || imageName == "veryhuo.com_pkp_178.jpg" || imageName == "veryhuo.com_pkp_193.jpg" || imageName == "veryhuo.com_pkp_207.jpg" || imageName == "veryhuo.com_pkp_216.jpg" || imageName == "veryhuo.com_pkp_22.jpg" || imageName == "veryhuo.com_pkp_230.jpg" || imageName == "veryhuo.com_pkp_245.jpg" || imageName == "veryhuo.com_pkp_259.jpg" || imageName == "veryhuo.com_pkp_268.jpg" || imageName == "veryhuo.com_pkp_282.jpg" || imageName == "veryhuo.com_pkp_297.jpg" || imageName == "veryhuo.com_pkp_311.jpg" || imageName == "veryhuo.com_pkp_320.jpg" || imageName == "veryhuo.com_pkp_334.jpg" || imageName == "veryhuo.com_pkp_349.jpg" || imageName == "veryhuo.com_pkp_363.jpg" || imageName == "veryhuo.com_pkp_37.jpg" || imageName == "veryhuo.com_pkp_372.jpg" || imageName == "veryhuo.com_pkp_386.jpg" || imageName == "veryhuo.com_pkp_401.jpg" || imageName == "veryhuo.com_pkp_415.jpg" || imageName == "veryhuo.com_pkp_51.jpg" || imageName == "veryhuo.com_pkp_60.jpg" || imageName == "veryhuo.com_pkp_74.jpg" || imageName == "veryhuo.com_pkp_8.jpg" || imageName == "veryhuo.com_pkp_89.jpg") {
        s = 2;
    } else if (imageName == "veryhuo.com_pkp_113.jpg" || imageName == "veryhuo.com_pkp_127.jpg" || imageName == "veryhuo.com_pkp_128.jpg" || imageName == "veryhuo.com_pkp_142.jpg" || imageName == "veryhuo.com_pkp_165.jpg" || imageName == "veryhuo.com_pkp_179.jpg" || imageName == "veryhuo.com_pkp_180.jpg" || imageName == "veryhuo.com_pkp_194.jpg" || imageName == "veryhuo.com_pkp_217.jpg" || imageName == "veryhuo.com_pkp_23.jpg" || imageName == "veryhuo.com_pkp_231.jpg" || imageName == "veryhuo.com_pkp_232.jpg" || imageName == "veryhuo.com_pkp_24.jpg" || imageName == "veryhuo.com_pkp_246.jpg" || imageName == "veryhuo.com_pkp_269.jpg" || imageName == "veryhuo.com_pkp_283.jpg" || imageName == "veryhuo.com_pkp_284.jpg" || imageName == "veryhuo.com_pkp_298.jpg" || imageName == "veryhuo.com_pkp_321.jpg" || imageName == "veryhuo.com_pkp_335.jpg" || imageName == "veryhuo.com_pkp_336.jpg" || imageName == "veryhuo.com_pkp_350.jpg" || imageName == "veryhuo.com_pkp_373.jpg" || imageName == "veryhuo.com_pkp_38.jpg" || imageName == "veryhuo.com_pkp_387.jpg" || imageName == "veryhuo.com_pkp_388.jpg" || imageName == "veryhuo.com_pkp_402.jpg" || imageName == "veryhuo.com_pkp_61.jpg" || imageName == "veryhuo.com_pkp_75.jpg" || imageName == "veryhuo.com_pkp_76.jpg" || imageName == "veryhuo.com_pkp_9.jpg" || imageName == "veryhuo.com_pkp_90.jpg") {
        s = 3;
    } else if (imageName == "veryhuo.com_pkp_10.jpg" || imageName == "veryhuo.com_pkp_114.jpg" || imageName == "veryhuo.com_pkp_129.jpg" || imageName == "veryhuo.com_pkp_139.jpg" || imageName == "veryhuo.com_pkp_143.jpg" || imageName == "veryhuo.com_pkp_166.jpg" || imageName == "veryhuo.com_pkp_181.jpg" || imageName == "veryhuo.com_pkp_191.jpg" || imageName == "veryhuo.com_pkp_195.jpg" || imageName == "veryhuo.com_pkp_218.jpg" || imageName == "veryhuo.com_pkp_233.jpg" || imageName == "veryhuo.com_pkp_243.jpg" || imageName == "veryhuo.com_pkp_247.jpg" || imageName == "veryhuo.com_pkp_25.jpg" || imageName == "veryhuo.com_pkp_270.jpg" || imageName == "veryhuo.com_pkp_285.jpg" || imageName == "veryhuo.com_pkp_295.jpg" || imageName == "veryhuo.com_pkp_299.jpg" || imageName == "veryhuo.com_pkp_322.jpg" || imageName == "veryhuo.com_pkp_337.jpg" || imageName == "veryhuo.com_pkp_347.jpg" || imageName == "veryhuo.com_pkp_35.jpg" || imageName == "veryhuo.com_pkp_351.jpg" || imageName == "veryhuo.com_pkp_374.jpg" || imageName == "veryhuo.com_pkp_389.jpg" || imageName == "veryhuo.com_pkp_39.jpg" || imageName == "veryhuo.com_pkp_399.jpg" || imageName == "veryhuo.com_pkp_403.jpg" || imageName == "veryhuo.com_pkp_62.jpg" || imageName == "veryhuo.com_pkp_77.jpg" || imageName == "veryhuo.com_pkp_87.jpg" || imageName == "veryhuo.com_pkp_91.jpg") {
        s = 4;
    } else if (imageName == "veryhuo.com_pkp_11.jpg" || imageName == "veryhuo.com_pkp_115.jpg" || imageName == "veryhuo.com_pkp_130.jpg" || imageName == "veryhuo.com_pkp_144.jpg" || imageName == "veryhuo.com_pkp_150.jpg" || imageName == "veryhuo.com_pkp_167.jpg" || imageName == "veryhuo.com_pkp_182.jpg" || imageName == "veryhuo.com_pkp_196.jpg" || imageName == "veryhuo.com_pkp_202.jpg" || imageName == "veryhuo.com_pkp_219.jpg" || imageName == "veryhuo.com_pkp_234.jpg" || imageName == "veryhuo.com_pkp_248.jpg" || imageName == "veryhuo.com_pkp_254.jpg" || imageName == "veryhuo.com_pkp_26.jpg" || imageName == "veryhuo.com_pkp_271.jpg" || imageName == "veryhuo.com_pkp_286.jpg" || imageName == "veryhuo.com_pkp_300.jpg" || imageName == "veryhuo.com_pkp_306.jpg" || imageName == "veryhuo.com_pkp_323.jpg" || imageName == "veryhuo.com_pkp_338.jpg" || imageName == "veryhuo.com_pkp_352.jpg" || imageName == "veryhuo.com_pkp_358.jpg" || imageName == "veryhuo.com_pkp_375.jpg" || imageName == "veryhuo.com_pkp_390.jpg" || imageName == "veryhuo.com_pkp_40.jpg" || imageName == "veryhuo.com_pkp_404.jpg" || imageName == "veryhuo.com_pkp_410.jpg" || imageName == "veryhuo.com_pkp_46.jpg" || imageName == "veryhuo.com_pkp_63.jpg" || imageName == "veryhuo.com_pkp_78.jpg" || imageName == "veryhuo.com_pkp_92.jpg" || imageName == "veryhuo.com_pkp_98.jpg") {
        s = 5;
    } else if (imageName == "veryhuo.com_pkp_104.jpg" || imageName == "veryhuo.com_pkp_116.jpg" || imageName == "veryhuo.com_pkp_12.jpg" || imageName == "veryhuo.com_pkp_131.jpg" || imageName == "veryhuo.com_pkp_145.jpg" || imageName == "veryhuo.com_pkp_156.jpg" || imageName == "veryhuo.com_pkp_168.jpg" || imageName == "veryhuo.com_pkp_183.jpg" || imageName == "veryhuo.com_pkp_197.jpg" || imageName == "veryhuo.com_pkp_208.jpg" || imageName == "veryhuo.com_pkp_220.jpg" || imageName == "veryhuo.com_pkp_235.jpg" || imageName == "veryhuo.com_pkp_249.jpg" || imageName == "veryhuo.com_pkp_260.jpg" || imageName == "veryhuo.com_pkp_27.jpg" || imageName == "veryhuo.com_pkp_272.jpg" || imageName == "veryhuo.com_pkp_287.jpg" || imageName == "veryhuo.com_pkp_301.jpg" || imageName == "veryhuo.com_pkp_312.jpg" || imageName == "veryhuo.com_pkp_324.jpg" || imageName == "veryhuo.com_pkp_339.jpg" || imageName == "veryhuo.com_pkp_353.jpg" || imageName == "veryhuo.com_pkp_364.jpg" || imageName == "veryhuo.com_pkp_376.jpg" || imageName == "veryhuo.com_pkp_391.jpg" || imageName == "veryhuo.com_pkp_405.jpg" || imageName == "veryhuo.com_pkp_41.jpg" || imageName == "veryhuo.com_pkp_416.jpg" || imageName == "veryhuo.com_pkp_52.jpg" || imageName == "veryhuo.com_pkp_64.jpg" || imageName == "veryhuo.com_pkp_79.jpg" || imageName == "veryhuo.com_pkp_93.jpg") {
        s = 6;
    } else if (imageName == "veryhuo.com_pkp_106.jpg" || imageName == "veryhuo.com_pkp_118.jpg" || imageName == "veryhuo.com_pkp_132.jpg" || imageName == "veryhuo.com_pkp_14.jpg" || imageName == "veryhuo.com_pkp_146.jpg" || imageName == "veryhuo.com_pkp_158.jpg" || imageName == "veryhuo.com_pkp_170.jpg" || imageName == "veryhuo.com_pkp_184.jpg" || imageName == "veryhuo.com_pkp_198.jpg" || imageName == "veryhuo.com_pkp_2.jpg" || imageName == "veryhuo.com_pkp_210.jpg" || imageName == "veryhuo.com_pkp_222.jpg" || imageName == "veryhuo.com_pkp_236.jpg" || imageName == "veryhuo.com_pkp_250.jpg" || imageName == "veryhuo.com_pkp_262.jpg" || imageName == "veryhuo.com_pkp_274.jpg" || imageName == "veryhuo.com_pkp_28.jpg" || imageName == "veryhuo.com_pkp_288.jpg" || imageName == "veryhuo.com_pkp_302.jpg" || imageName == "veryhuo.com_pkp_314.jpg" || imageName == "veryhuo.com_pkp_326.jpg" || imageName == "veryhuo.com_pkp_340.jpg" || imageName == "veryhuo.com_pkp_354.jpg" || imageName == "veryhuo.com_pkp_366.jpg" || imageName == "veryhuo.com_pkp_378.jpg" || imageName == "veryhuo.com_pkp_392.jpg" || imageName == "veryhuo.com_pkp_406.jpg" || imageName == "veryhuo.com_pkp_42.jpg" || imageName == "veryhuo.com_pkp_54.jpg" || imageName == "veryhuo.com_pkp_66.jpg" || imageName == "veryhuo.com_pkp_80.jpg" || imageName == "veryhuo.com_pkp_94.jpg") {
        s = 7;
    } else if (imageName == "veryhuo.com_pkp_117.jpg" || imageName == "veryhuo.com_pkp_119.jpg" || imageName == "veryhuo.com_pkp_13.jpg" || imageName == "veryhuo.com_pkp_133.jpg" || imageName == "veryhuo.com_pkp_147.jpg" || imageName == "veryhuo.com_pkp_15.jpg" || imageName == "veryhuo.com_pkp_169.jpg" || imageName == "veryhuo.com_pkp_171.jpg" || imageName == "veryhuo.com_pkp_185.jpg" || imageName == "veryhuo.com_pkp_199.jpg" || imageName == "veryhuo.com_pkp_221.jpg" || imageName == "veryhuo.com_pkp_223.jpg" || imageName == "veryhuo.com_pkp_237.jpg" || imageName == "veryhuo.com_pkp_251.jpg" || imageName == "veryhuo.com_pkp_273.jpg" || imageName == "veryhuo.com_pkp_275.jpg" || imageName == "veryhuo.com_pkp_289.jpg" || imageName == "veryhuo.com_pkp_29.jpg" || imageName == "veryhuo.com_pkp_303.jpg" || imageName == "veryhuo.com_pkp_325.jpg" || imageName == "veryhuo.com_pkp_327.jpg" || imageName == "veryhuo.com_pkp_341.jpg" || imageName == "veryhuo.com_pkp_355.jpg" || imageName == "veryhuo.com_pkp_377.jpg" || imageName == "veryhuo.com_pkp_379.jpg" || imageName == "veryhuo.com_pkp_393.jpg" || imageName == "veryhuo.com_pkp_407.jpg" || imageName == "veryhuo.com_pkp_43.jpg" || imageName == "veryhuo.com_pkp_65.jpg" || imageName == "veryhuo.com_pkp_67.jpg" || imageName == "veryhuo.com_pkp_81.jpg" || imageName == "veryhuo.com_pkp_95.jpg") {
        s = 8;
    } else if (imageName == "veryhuo.com_pkp_1.jpg" || imageName == "veryhuo.com_pkp_105.jpg" || imageName == "veryhuo.com_pkp_120.jpg" || imageName == "veryhuo.com_pkp_134.jpg" || imageName == "veryhuo.com_pkp_148.jpg" || imageName == "veryhuo.com_pkp_157.jpg" || imageName == "veryhuo.com_pkp_16.jpg" || imageName == "veryhuo.com_pkp_172.jpg" || imageName == "veryhuo.com_pkp_186.jpg" || imageName == "veryhuo.com_pkp_200.jpg" || imageName == "veryhuo.com_pkp_209.jpg" || imageName == "veryhuo.com_pkp_224.jpg" || imageName == "veryhuo.com_pkp_238.jpg" || imageName == "veryhuo.com_pkp_252.jpg" || imageName == "veryhuo.com_pkp_261.jpg" || imageName == "veryhuo.com_pkp_276.jpg" || imageName == "veryhuo.com_pkp_290.jpg" || imageName == "veryhuo.com_pkp_30.jpg" || imageName == "veryhuo.com_pkp_304.jpg" || imageName == "veryhuo.com_pkp_313.jpg" || imageName == "veryhuo.com_pkp_328.jpg" || imageName == "veryhuo.com_pkp_342.jpg" || imageName == "veryhuo.com_pkp_356.jpg" || imageName == "veryhuo.com_pkp_365.jpg" || imageName == "veryhuo.com_pkp_380.jpg" || imageName == "veryhuo.com_pkp_394.jpg" || imageName == "veryhuo.com_pkp_408.jpg" || imageName == "veryhuo.com_pkp_44.jpg" || imageName == "veryhuo.com_pkp_53.jpg" || imageName == "veryhuo.com_pkp_68.jpg" || imageName == "veryhuo.com_pkp_82.jpg" || imageName == "veryhuo.com_pkp_96.jpg") {
        s = 9;
    } else if (imageName == "veryhuo.com_pkp_107.jpg" || imageName == "veryhuo.com_pkp_121.jpg" || imageName == "veryhuo.com_pkp_135.jpg" || imageName == "veryhuo.com_pkp_149.jpg" || imageName == "veryhuo.com_pkp_159.jpg" || imageName == "veryhuo.com_pkp_17.jpg" || imageName == "veryhuo.com_pkp_173.jpg" || imageName == "veryhuo.com_pkp_187.jpg" || imageName == "veryhuo.com_pkp_201.jpg" || imageName == "veryhuo.com_pkp_211.jpg" || imageName == "veryhuo.com_pkp_225.jpg" || imageName == "veryhuo.com_pkp_239.jpg" || imageName == "veryhuo.com_pkp_253.jpg" || imageName == "veryhuo.com_pkp_263.jpg" || imageName == "veryhuo.com_pkp_277.jpg" || imageName == "veryhuo.com_pkp_291.jpg" || imageName == "veryhuo.com_pkp_3.jpg" || imageName == "veryhuo.com_pkp_305.jpg" || imageName == "veryhuo.com_pkp_31.jpg" || imageName == "veryhuo.com_pkp_315.jpg" || imageName == "veryhuo.com_pkp_329.jpg" || imageName == "veryhuo.com_pkp_343.jpg" || imageName == "veryhuo.com_pkp_357.jpg" || imageName == "veryhuo.com_pkp_367.jpg" || imageName == "veryhuo.com_pkp_381.jpg" || imageName == "veryhuo.com_pkp_395.jpg" || imageName == "veryhuo.com_pkp_409.jpg" || imageName == "veryhuo.com_pkp_45.jpg" || imageName == "veryhuo.com_pkp_55.jpg" || imageName == "veryhuo.com_pkp_69.jpg" || imageName == "veryhuo.com_pkp_83.jpg" || imageName == "veryhuo.com_pkp_97.jpg") {
        s = 10;
    } else if (imageName == "veryhuo.com_pkp_108.jpg" || imageName == "veryhuo.com_pkp_122.jpg" || imageName == "veryhuo.com_pkp_136.jpg" || imageName == "veryhuo.com_pkp_151.jpg" || imageName == "veryhuo.com_pkp_160.jpg" || imageName == "veryhuo.com_pkp_174.jpg" || imageName == "veryhuo.com_pkp_18.jpg" || imageName == "veryhuo.com_pkp_188.jpg" || imageName == "veryhuo.com_pkp_203.jpg" || imageName == "veryhuo.com_pkp_212.jpg" || imageName == "veryhuo.com_pkp_226.jpg" || imageName == "veryhuo.com_pkp_240.jpg" || imageName == "veryhuo.com_pkp_255.jpg" || imageName == "veryhuo.com_pkp_264.jpg" || imageName == "veryhuo.com_pkp_278.jpg" || imageName == "veryhuo.com_pkp_292.jpg" || imageName == "veryhuo.com_pkp_307.jpg" || imageName == "veryhuo.com_pkp_316.jpg" || imageName == "veryhuo.com_pkp_32.jpg" || imageName == "veryhuo.com_pkp_330.jpg" || imageName == "veryhuo.com_pkp_344.jpg" || imageName == "veryhuo.com_pkp_359.jpg" || imageName == "veryhuo.com_pkp_368.jpg" || imageName == "veryhuo.com_pkp_382.jpg" || imageName == "veryhuo.com_pkp_396.jpg" || imageName == "veryhuo.com_pkp_4.jpg" || imageName == "veryhuo.com_pkp_411.jpg" || imageName == "veryhuo.com_pkp_47.jpg" || imageName == "veryhuo.com_pkp_56.jpg" || imageName == "veryhuo.com_pkp_70.jpg" || imageName == "veryhuo.com_pkp_84.jpg" || imageName == "veryhuo.com_pkp_99.jpg") {
        s = 11;
    } else if (imageName == "veryhuo.com_pkp_100.jpg" || imageName == "veryhuo.com_pkp_109.jpg" || imageName == "veryhuo.com_pkp_123.jpg" || imageName == "veryhuo.com_pkp_137.jpg" || imageName == "veryhuo.com_pkp_152.jpg" || imageName == "veryhuo.com_pkp_161.jpg" || imageName == "veryhuo.com_pkp_175.jpg" || imageName == "veryhuo.com_pkp_189.jpg" || imageName == "veryhuo.com_pkp_19.jpg" || imageName == "veryhuo.com_pkp_204.jpg" || imageName == "veryhuo.com_pkp_213.jpg" || imageName == "veryhuo.com_pkp_227.jpg" || imageName == "veryhuo.com_pkp_241.jpg" || imageName == "veryhuo.com_pkp_256.jpg" || imageName == "veryhuo.com_pkp_265.jpg" || imageName == "veryhuo.com_pkp_279.jpg" || imageName == "veryhuo.com_pkp_293.jpg" || imageName == "veryhuo.com_pkp_308.jpg" || imageName == "veryhuo.com_pkp_317.jpg" || imageName == "veryhuo.com_pkp_33.jpg" || imageName == "veryhuo.com_pkp_331.jpg" || imageName == "veryhuo.com_pkp_345.jpg" || imageName == "veryhuo.com_pkp_360.jpg" || imageName == "veryhuo.com_pkp_369.jpg" || imageName == "veryhuo.com_pkp_383.jpg" || imageName == "veryhuo.com_pkp_397.jpg" || imageName == "veryhuo.com_pkp_412.jpg" || imageName == "veryhuo.com_pkp_48.jpg" || imageName == "veryhuo.com_pkp_5.jpg" || imageName == "veryhuo.com_pkp_57.jpg" || imageName == "veryhuo.com_pkp_71.jpg" || imageName == "veryhuo.com_pkp_85.jpg") {
        s = 12;
    } else if (imageName == "veryhuo.com_pkp_101.jpg" || imageName == "veryhuo.com_pkp_110.jpg" || imageName == "veryhuo.com_pkp_124.jpg" || imageName == "veryhuo.com_pkp_138.jpg" || imageName == "veryhuo.com_pkp_153.jpg" || imageName == "veryhuo.com_pkp_162.jpg" || imageName == "veryhuo.com_pkp_176.jpg" || imageName == "veryhuo.com_pkp_190.jpg" || imageName == "veryhuo.com_pkp_20.jpg" || imageName == "veryhuo.com_pkp_205.jpg" || imageName == "veryhuo.com_pkp_214.jpg" || imageName == "veryhuo.com_pkp_228.jpg" || imageName == "veryhuo.com_pkp_242.jpg" || imageName == "veryhuo.com_pkp_257.jpg" || imageName == "veryhuo.com_pkp_266.jpg" || imageName == "veryhuo.com_pkp_280.jpg" || imageName == "veryhuo.com_pkp_294.jpg" || imageName == "veryhuo.com_pkp_309.jpg" || imageName == "veryhuo.com_pkp_318.jpg" || imageName == "veryhuo.com_pkp_332.jpg" || imageName == "veryhuo.com_pkp_34.jpg" || imageName == "veryhuo.com_pkp_346.jpg" || imageName == "veryhuo.com_pkp_361.jpg" || imageName == "veryhuo.com_pkp_370.jpg" || imageName == "veryhuo.com_pkp_384.jpg" || imageName == "veryhuo.com_pkp_398.jpg" || imageName == "veryhuo.com_pkp_413.jpg" || imageName == "veryhuo.com_pkp_49.jpg" || imageName == "veryhuo.com_pkp_58.jpg" || imageName == "veryhuo.com_pkp_6.jpg" || imageName == "veryhuo.com_pkp_72.jpg" || imageName == "veryhuo.com_pkp_86.jpg") {
        s = 13;
    }
    return s;
}

function showData(data) {
    if (data > 9) {
        return 0
    } else {
        return data;
    }
}

function showData2(data) {
    if (data == '') {
        return '';
    }
    if (data < 10 && data > 1) {
        return data;
    } else if (data == 10) {
        return '10';
    } else if (data == 11) {
        return 'J';
    } else if (data == 12) {
        return 'Q';
    } else if (data == 13) {
        return 'K';
    } else if (data == 1) {
        return "A";
    } else {
        return "";
    }
}

function formatDate(date, format) {
    if (!date) {
        return '';
    }
    else if (typeof(date) == "string") {
        if ("null" == date) {
            return '';
        }
        return date;
    }
    else if (typeof(date) == "undefined" || "undefined" == date) {
        return '';
    }
    else if (typeof(date) == "object") {
        var year = date.year + 1900;
        var month = (date.month + 1) >= 10 ? (date.month + 1) : "0" + (date.month + 1);
        var day = date.date >= 10 ? date.date : "0" + date.date;
        var hours = date.hours >= 10 ? date.hours : "0" + date.hours;
        var minutes = date.minutes >= 10 ? date.minutes : "0" + date.minutes;
        var seconds = date.seconds >= 10 ? date.seconds : "0" + date.seconds;
        if (format && "hh:mi:ss" == format) {
            return hours + ":" + minutes + ":" + seconds
        }
        else if (format && "yyyy-mm-dd" == format) {
            return year + "-" + month + "-" + day
        }
        else if (format && "yyyy-mm-dd hh:mi:ss" == format) {
            return year + "-" + month + "-" + day + " " + hours + ":" + minutes + ":" + seconds
        }
        else if (format && "yyyy/mm/dd" == format) {
            return year + "/" + month + "/" + day
        }
        else if (format && "yyyy/mm/dd hh:mi:ss" == format) {
            return year + "/" + month + "/" + day + " " + hours + ":" + minutes + ":" + seconds
        }
        return year + "-" + month + "-" + day + " " + hours + ":" + minutes + ":" + seconds;
    }
    return date;
}